### ISSUE TITLE
Tensorflow v2.1

### ISSUE THREAD

**Issue by LBerth** [metwork-framework/mfextaddon_python3_ia#24]
Hi !

Current version of tensorflow is v 1.14. Would it be possible to upgrade to v 2.1 ?

Léa

**Comment by thebaptiste** [comment]
Do you need exactly version 2.1 ?
I ask because versions 2.2 and 2.3 are also available, but they introduce breaking changes...
See [here](https://github.com/tensorflow/tensorflow/releases)

**Comment by LBerth** [comment]
I didn't know there were later versions. 
I checked and the breaking changes should not be a problem, so the latest version is the best.
Thanks

**Comment by thebaptiste** [comment]
So I will try to build version 2.3. I hope there will be no build or dependencies difficulties.

**Comment by thebaptiste** [comment]
I spent more than a week trying to build Tensorflow 2.3 or 2.1 in Metwork but I didn't succeed. There are complex interactions between bazel (used to build tensorflow), gcc/g++ 8 (compilators used in Metwork with devtoolset-8) and tensorflow sources.
Unless I get help from a bazel/tensorflow guru, I give up for the time being.

**Comment by thebaptiste** [comment]
Thanks to several changes in mfext, it has been possible to install tensorflow in Metwork without building it from sources.
So it has been possible to upgrade tensorflow to the last available version : 2.4.1.

**Comment by LBerth** [comment]
Great ! Thank you very much, I will test it as soon as I can ! :)

**Comment by thebaptiste** [comment]
For the time being, it will only be available on the master branch (from tomorrow).
It will be officialy released with Metwork 1.1 (I don't know when, probably not very soon)

**Comment by thebaptiste** [comment]
We are now providing tensorflow 2.5.0 (master branch), in order to fix a security vulnerability (see #66)
