### ISSUE TITLE
mfextaddon_python3_ia should not need pre-installed mfextaddon_scientific to compile

### ISSUE THREAD

**Issue by thebaptiste** [metwork-framework/mfextaddon_python3_ia#4]
There should be no dependencies at build between mfext addons because we don't want to manage triggers in mfext addons.
In this case mfextaddon_python3_ia needs mfextaddon_scientific for numpy and scipy
This dependency is explicit in drone.yml (but there is no trigger to rebuild mfextaddon_python3_ia at the end of the build of mfextaddon_scientific)

We should do otherwise.

**Comment by thefab** [comment]
we are finally not sure about that

let's close it for the moment
